[build]
    command = "npm ci && npm run build"
    publish = "dist"

[build.environment]
    NODE_VERSION = "22.14.0"

# [[headers]]
#     for = "/*"
#     [headers.values]
#         Access-Control-Allow-Origin = "https://name-of-frontend-url.netlify.app"
